### ISSUE TITLE
Code wont run without errors

### ISSUE THREAD

**Issue by Tdannen** [QuantLet/QID-1679-MVAdrugLogistic#1]

**Comment by polarstern** [comment]
code has been changed, now it runs without errors.

**Comment by Tdannen** [comment]
images have no description.

**Comment by polarstern** [comment]
Done. 
![mvadruglogistic_1-1](https://cloud.githubusercontent.com/assets/14127572/9980951/2cc90886-5fad-11e5-8c90-8eb5b675d155.png)
![mvadruglogistic_2-1](https://cloud.githubusercontent.com/assets/14127572/9980953/2f03dfd6-5fad-11e5-907f-a3d0b936f530.png)

**Comment by lborke** [comment]
I have checked the Code.
No errors!

Can we close this issue?
